services:
  velocity:
    image: eclipse-temurin:21-jre
    container_name: flashbyte-proxy
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /server

    entrypoint: ["java", "-Xms1G", "-Xmx1G", "-jar", "/server/flashbyte.jar"]

    ports:
      - "25565:25577"

    volumes:
      - ./run:/server

    networks:
      - master

networks:
  master:
    external: true
    name: master-backend_master
